### ISSUE TITLE
Произведение векторов

### ISSUE THREAD

**Issue by avasyukov** [d-qql/Linal_Task#1]
Предполагалось, что произведение двух векторов - скалярное, а не покоординатное.
Это не критично, но таки нужно поправить. Сейчас получается:
```
A = (1; 2; 3)
B = (1; 1; 1)
A * B = (1; 2; 3)
```

**Comment by d-qql** [comment]
fixed

**Comment by avasyukov** [comment]
Подтверждаю, поправлено
