### ISSUE TITLE
new / delete

### ISSUE THREAD

**Issue by avasyukov** [d-qql/Linal_Task#3]
Вот этот delete:
https://github.com/d-qql/Linal_Task/blob/e8e347ff152a5831b5b7dfc78a17f335d519eebc/main.cpp#L87
Тоже должен быть в форме delete[], так как удаляем тоже массив.

**Comment by d-qql** [comment]
fixed commit #4

**Comment by avasyukov** [comment]
Подтверждаю, поправлено
