### ISSUE TITLE
Фэн-шуй на const-овость

### ISSUE THREAD

**Issue by avasyukov** [d-qql/Linal_Task#4]
Этот тикет - самые последние штрихи на линал.

Сейчас почти у всех операторов:
- указана const-овость в отношении текущего объекта (this-а) -- это правильно
- не указана const-овость в отношении второго операнда (параметр, переданный по ссылке) -- логически она ожидается, так что в коде её нужно добавить
- указана const-овость в отношении возвращаемого значения -- это творческий вопрос, можно оставить, можно убрать, любой вариант будет засчитан

(Но нужно быть готовым, что именно про const-овость в отношении возвращаемого значения я спрошу на финальной стадии зачёта - на что она влияет и почему.)

**Comment by d-qql** [comment]
Hope I fixed it

**Comment by avasyukov** [comment]
Да, всё стало ок.
